COMPUTER PYTHON PRACTICAL FILE :
ASHMIT ANAND IX C
Please refer textbook for questions:

In [1]:
#program 1
a=float(input('Enter 1st number: '))
b=float(input('Enter 2nd number: '))
c=float(input('Enter 3rd number: '))

print('The sum of the numbers is: ',a+b+c,'The product of the numbers is: ',a*b*c)

Enter 1st number: 1
Enter 2nd number: 2
Enter 3rd number: 3
The sum of the numbers is:  6.0 The product of the numbers is:  6.0

In [2]:
#program 2
#factorial of a number is the number multiplied by its predecessors till 1
#so factorial of 10 would ve 10*9*8*&*6*5*4*3*2*1

print('The factorial of 10 is: ',10*9*8*7*6*5*4*3*2*1)

The factorial of 10 is:  3628800

In [3]:
#program 3
a=float(input('Eneter the 1st number: '))
        
b=float(input('Enter the 2nd number: '))

a=a*-1
b=b*-1
print(a,b)

Eneter the 1st number: 1
Enter the 2nd number: -2
-1.0 2.0

In [4]:
#program 4
list=[29, 'December', 20.07]
print('The data type of 1st item is: '+str(type(list[0])))
print('The data type of 2nd item is: '+str(type(list[1])))
print('The data type of 3rd item is: '+str(type(list[2])))

The data type of 1st item is: <class 'int'>
The data type of 2nd item is: <class 'str'>
The data type of 3rd item is: <class 'float'>

In [5]:
#program 5
list=[1,2,3,3.5,5]
print(list[4],'>', list[3],'>',list[2],'>', list[1],'>', list[0])

5 > 3.5 > 3 > 2 > 1

In [6]:
#program 6
list=[1,3,5,7]
list[2]=list[0]*list[1]
list[3]=list[2]*list[1]
print(list)

[1, 3, 3, 9]

In [7]:
#program 7
list=[1,2,3,4,5,6]
list[1]=list[0]*list[0]*list[0]
list[3]=list[2]*list[2]*list[2]
list[5]=list[4]*list[4]*list[4]
print(list)

[1, 1, 3, 27, 5, 125]

In [8]:
#program 8
print('Enter 1st number')
list=[int(input())]
print('Enter 2nd number')
list.append(int(input()))
print('Enter 3rd number')
list.append(int(input()))
print('The product of these numbers is: ' +str(list[0]*list[1]*list[2]))

Enter 1st number
1
Enter 2nd number
2
Enter 3rd number
3
The product of these numbers is: 6

In [9]:
#program 9
a=float(input())
list=[a*1]
list.append(a*2)
list.append(a*3)
print(list)

2
[2.0, 4.0, 6.0]

In [10]:
#program 10
print('Enter the 1st name: ')
list=[input()]

print('Enter the 2nd name: ')
list.append(input())

print('Enter the 3rd name: ')
list.append(input())

name=list[0]+' '+list[1]+' '+list[2]

print(name)
list.remove

Enter the 1st name:
ASH
Enter the 2nd name:
mit
Enter the 3rd name:
anand
ASH mit anand

In [11]:
#program 11
a=float(input('Enter 1st number: '))
b=float(input('Enter 2nd number: '))
sums=a+b
sub=a-b
print('The sum is: ', sums)
print('The difference is: ', sub)

Enter 1st number: 10
Enter 2nd number: 11
The sum is:  21.0
The difference is:  -1.0

In [12]:
#program 12
a=float(input('Enter 1st number: '))
b=float(input('Enter 2nd number: '))
mul=a*b
div=a/b
print('Product is: ', mul)
print('Quotient is: ', div)

Enter 1st number: 4
Enter 2nd number: 5
Product is:  20.0
Quotient is:  0.8

In [13]:
#program 13
#1mile=0.261km
km=float(input('Enter kilometres: '))
miles=km*0.621
print('Given input to miles is approx: ', miles)

Enter kilometres: 20
Given input to miles is approx:  12.42

In [14]:
#program 14
l=float(input('Enter length: '))
b=float(input('Enter breadth: '))

area= l*b
print('The area is: ', area, 'sq. units')

Enter length: 60
Enter breadth: 7
The area is:  420.0 sq. units

In [15]:
#program 15
k=float(input('Enter temperature in Kelvin: '))
f=k-273
print('The given temperature in kelvin is:',f,'Celsius')

Enter temperature in Kelvin: 500
The given temperature in kelvin is: 227.0 Celsius

In [16]:
#program 16
k=float(input('Enter temperature in Celsius: '))
f=(k*1.8)+32
print('The given temperature in kelvin is:',f,'Fahrenheit')

Enter temperature in Celsius: 100
The given temperature in kelvin is: 212.0 Fahrenheit

In [17]:
#program 17
feet=float(input('Enter height in feet: '))
inch=feet*12
print(feet,'feet is',inch,'inches')

Enter height in feet: 10
10.0 feet is 120.0 inches

In [18]:
#program 18
i=float(input('Enter current(in coulomb): '))
r=float(input('Enter resistance(in ohm): '))
v=i*r
print('The voltage is: ', v )

Enter current(in coulomb): 220
Enter resistance(in ohm): 40
The voltage is:  8800.0

In [19]:
#program 19
a=float(input('Enter 1st number: '))
b=float(input('Enter 2nd number: '))
quotient=a//b
remainder=a%b
print('Quotient is: ',quotient)
print('Remainder is: ',remainder)

Enter 1st number: 50
Enter 2nd number: 5
Quotient is:  10.0
Remainder is:  0.0

In [20]:
#program 20
a=input('Area of lan in sq.metres: ')
b=input('Number of people in that area: ')
density=float(b)/float(a)

print('Population density = ', density)

Area of lan in sq.metres: 500000
Number of people in that area: 123423
Population density =  0.246846

In [21]:
#program 21
#mileage of a vehicle
km = input('Distance travelled by vehicle(in km): ')
petrol=input('Amount of fuel used for trip (in litres): ')
mileage = float(km)/float(petrol)

print('Mileage of the vehicle is: ', mileage)

Distance travelled by vehicle(in km): 10234
Amount of fuel used for trip (in litres): 5000
Mileage of the vehicle is:  2.0468

End